# Generated by Django 4.1.5 on 2023-01-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="generated_password",
            field=models.CharField(max_length=9, verbose_name="Generated Password"),
        ),
    ]
