# Generated by Django 4.1.5 on 2023-01-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="date_updated",
        ),
    ]
