# Generated by Django 4.1.5 on 2023-01-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_score_date_updated"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Score",
        ),
    ]
