# Generated by Django 4.1.5 on 2023-02-04 03:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="option",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Option"
            ),
        ),
    ]
