# Generated by Django 4.1.5 on 2023-01-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="subject",
        ),
    ]
