# Generated by Django 4.1.5 on 2023-01-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_quiz_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz",
            field=models.CharField(max_length=255, verbose_name="Quiz Title"),
        ),
    ]
