# Generated by Django 4.1.5 on 2023-01-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_quiz_quiz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Score",
        ),
    ]
